name: solesphere
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http:
  intl:
  logger:
  url_launcher:
  flutter_svg:
  cupertino_icons:
  iconsax:
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  
  curved_labeled_navigation_bar: ^2.0.2
  floating_bottom_bar:
  flutter_rating_bar: ^4.0.1
  buttons_tabbar: ^1.3.8
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  carousel_slider: ^4.2.1
  lottie: ^3.1.0

  # Product Specific

#--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/home/
    - assets/icons/navigation/
    - assets/icons/profile/
    - assets/icons/search/
    - assets/icons/social/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/products/
    - assets/jsons/

   
  
  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
          weight: 300
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 500