name: solesphere
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1
  
  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
<<<<<<< HEAD
  smooth_page_indicator: ^1.1.0
  
=======
  curved_labeled_navigation_bar: ^2.0.2
  floating_bottom_bar: ^0.0.3
  flutter_rating_bar: ^4.0.1
>>>>>>> c87f241e056c228e76a1731abd1b9cff5f0e564f

  # Product Specific

#--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/home/
    - assets/icons/navigation/
    - assets/icons/profile/
    - assets/icons/search/
    - assets/icons/social/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/products/

   
  
  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
          weight: 300
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 500
    
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
