// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkBnpXCOyb-ZhjKG5utN3aMoyHqTw0EJk',
    appId: '1:946297687740:web:9efefbc2249ccedd79cab9',
    messagingSenderId: '946297687740',
    projectId: 'solesphere-app-73c2b',
    authDomain: 'solesphere-app-73c2b.firebaseapp.com',
    storageBucket: 'solesphere-app-73c2b.appspot.com',
    measurementId: 'G-5Y89Y023N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcstnhjCh89Z3w_ujwCttr2rpcfAppi58',
    appId: '1:946297687740:android:8ac8b0eb1b47482579cab9',
    messagingSenderId: '946297687740',
    projectId: 'solesphere-app-73c2b',
    storageBucket: 'solesphere-app-73c2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1BkTN8qTRKQ5gFdAcGPL7DQbAsKre08',
    appId: '1:946297687740:ios:1e13fb69dc4fb5c279cab9',
    messagingSenderId: '946297687740',
    projectId: 'solesphere-app-73c2b',
    storageBucket: 'solesphere-app-73c2b.appspot.com',
    androidClientId: '946297687740-6nkbe22l1umstekjsnhiv7qvmjlb8r58.apps.googleusercontent.com',
    iosClientId: '946297687740-vefaj2h12vbf84loprhrd8ntfnerqoui.apps.googleusercontent.com',
    iosBundleId: 'com.example.solesphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI1BkTN8qTRKQ5gFdAcGPL7DQbAsKre08',
    appId: '1:946297687740:ios:1e13fb69dc4fb5c279cab9',
    messagingSenderId: '946297687740',
    projectId: 'solesphere-app-73c2b',
    storageBucket: 'solesphere-app-73c2b.appspot.com',
    androidClientId: '946297687740-6nkbe22l1umstekjsnhiv7qvmjlb8r58.apps.googleusercontent.com',
    iosClientId: '946297687740-vefaj2h12vbf84loprhrd8ntfnerqoui.apps.googleusercontent.com',
    iosBundleId: 'com.example.solesphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkBnpXCOyb-ZhjKG5utN3aMoyHqTw0EJk',
    appId: '1:946297687740:web:a584e9f629a931a079cab9',
    messagingSenderId: '946297687740',
    projectId: 'solesphere-app-73c2b',
    authDomain: 'solesphere-app-73c2b.firebaseapp.com',
    storageBucket: 'solesphere-app-73c2b.appspot.com',
    measurementId: 'G-7D6Q63FXM6',
  );

}